# Generated by Django 4.1.3 on 2022-11-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extensionusuario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='extensionusuario',
            name='link',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
