# Generated by Django 4.1.3 on 2022-11-06 23:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
