# Generated by Django 4.1.3 on 2022-11-08 01:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_extensiofotos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExtensioFotos',
            new_name='ExtensionFotos',
        ),
    ]
