# Generated by Django 4.1.1 on 2022-11-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='fotos/')),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='descripcion',
        ),
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
