# Generated by Django 4.1.1 on 2022-11-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_fotos_remove_usuario_descripcion_delete_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotos',
            old_name='image',
            new_name='foto',
        ),
    ]
