# Generated by Django 4.1.1 on 2022-11-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_fotousuario_delete_fotos_usuario_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotousuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
