# Generated by Django 4.1.1 on 2022-11-08 17:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_fotousuario_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrep', models.CharField(max_length=30)),
                ('apellidop', models.CharField(max_length=30)),
                ('edadp', models.IntegerField()),
                ('fecha_nacimientop', models.DateField()),
                ('descripcion', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FotoUsuario',
        ),
    ]
