# Generated by Django 4.1.3 on 2022-11-08 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_delete_post_usuario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
    ]
