# Generated by Django 4.1.3 on 2022-11-09 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_usuario_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Post',
        ),
    ]
