# Generated by Django 4.1.3 on 2022-11-09 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_rename_usuario_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='descripcion',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='apellido',
            new_name='subtitulo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fecha_nacimiento',
        ),
    ]
