# Generated by Django 4.1.3 on 2022-11-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_rename_descripcion_post_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
    ]
