# Generated by Django 4.1.3 on 2022-11-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_post_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
