# Generated by Django 4.1.1 on 2022-11-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_post_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
    ]
