# Generated by Django 4.1.3 on 2022-11-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_post_autor_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='autor',
        ),
    ]
